apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overpass-data-pvc
  namespace: {{ .Release.Namespace }}

spec:
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
