{{- if .Values.metrics.enabled }}
{{- if eq .Values.database.backend "cnpg" }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: georef-db
  labels:
    app: georeference-tool
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: georef-db
  podMetricsEndpoints:
    - port: metrics
{{- end }}
{{- end }}
{{- end }}
