{{- $pvcExists := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace "yesterdays-clip-cache") }}
{{- if not $pvcExists }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yesterdays-clip-cache
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.clip.storageClass }}
  resources:
    requests:
      storage: {{ .Values.clip.size }}
{{- end }}
