apiVersion: v1
kind: Service
metadata:
  name: georeference-tool
  namespace: {{ .Release.Namespace }}
  labels:
    app: georeference-tool
spec:
  type: ClusterIP
  selector:
    app: georeference-tool
  ports:
    - name: http
      port: 80
      targetPort: 8000
