apiVersion: v1
kind: Service
metadata:
  name: yesterdays
  namespace: {{ .Release.Namespace }}
  labels:
    app: georeference-tool
spec:
  type: ClusterIP
  selector:
    app: yesterdays-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: metrics
      port: 9090
      targetPort: 9090
