apiVersion: batch/v1
kind: Job
metadata:
  name: georef-clip-download
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 3600 # one hour
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          command:
            ["uv", "run", "manage.py", "download_clip_model"]
          volumeMounts:
            - name: clip-cache
              mountPath: /cache
      volumes:
        - name: clip-cache
          persistentVolumeClaim:
            claimName: georef-clip-cache
