apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: georef-clip-cache
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.clip.storageClass }}
  resources:
    requests:
      storage: {{ .Values.clip.size }}
