{{- if .Values.tasks.beat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: yesterdays-celery-beat
  template:
    metadata:
      labels:
        app: yesterdays-celery-beat
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: celery-beat
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          command: ["uv"]
          args:
            - "run"
            - "celery"
            - "-A"
            - "yesterdays"
            - "beat"
            - "--loglevel=info"
          env:
            - name: DJANGO_TIME_ZONE
              value: {{ .Values.django.timeZone }}
            - name: DJANGO_SECRET_KEY
              value: {{ .Values.django.secretKey }}
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ .Values.django.allowedHosts }}
            - name: DJANGO_DEBUG
              value: "{{ .Values.django.debug }}"
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: host
            - name: PG_DBNAME
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: dbname
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: port
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: password
            - name: RABBITMQ_HOST
              value: "yesterdays-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: yesterdays-rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yesterdays-rabbitmq-default-user
                  key: password
            - name: CELERY_BROKER_URL
              value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)//"
            - name: METADATA_REFRESH_WIKIDATA_RATE_LIMIT
              value: {{ .Values.metadataRefresh.wikidataRateLimit | quote }}
            - name: METADATA_REFRESH_OSM_RATE_LIMIT
              value: {{ .Values.metadataRefresh.osmRateLimit | quote }}
            - name: METADATA_REFRESH_STALE_DAYS
              value: {{ .Values.metadataRefresh.staleDays | quote }}
            - name: METADATA_REFRESH_MAX_FAILURES
              value: {{ .Values.metadataRefresh.maxFailures | quote }}
            - name: METADATA_REFRESH_POSTPASS_URL
              value: {{ .Values.metadataRefresh.postpassUrl | quote }}
            - name: METADATA_REFRESH_POSTPASS_TIMEOUT
              value: {{ .Values.metadataRefresh.postpassTimeout | quote }}
            - name: METADATA_REFRESH_POSTPASS_BBOX
              value: {{ .Values.metadataRefresh.postpassBbox | quote }}
{{- end }}
